package systm_web.account;

import systm_web.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar. 
// </auto-generated>
//------------------------------------------------------------------------------


public class Login extends Page
{
	protected final void Page_Load(Object sender, tangible.EventArgs e)
	{
		RegisterHyperLink.NavigateUrl = "Register.aspx";
		OpenAuthLogin.setReturnUrl(Request.QueryString["ReturnUrl"]);

		var returnUrl = HttpUtility.UrlEncode(Request.QueryString["ReturnUrl"]);
		if (!tangible.StringHelper.isNullOrEmpty(returnUrl))
		{
			RegisterHyperLink.NavigateUrl += "?ReturnUrl=" + returnUrl;
		}
	}



	/** 
	 RegisterHyperLink control.
	 
	 
	 Auto-generated field.
	 To modify move field declaration from designer file to code-behind file.
	 
	*/
	protected System.Web.UI.WebControls.HyperLink RegisterHyperLink;

	/** 
	 OpenAuthLogin control.
	 
	 
	 Auto-generated field.
	 To modify move field declaration from designer file to code-behind file.
	 
	*/
	protected systm_web.account.OpenAuthProviders OpenAuthLogin;
}