package systm_web.account;

import systm_web.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar. 
// </auto-generated>
//------------------------------------------------------------------------------


public class OpenAuthProviders extends System.Web.UI.UserControl
{
	protected final void Page_Load(Object sender, tangible.EventArgs e)
	{

		if (IsPostBack)
		{
			var provider = Request.Form["provider"];
			if (provider == null)
			{
				return;
			}

			var redirectUrl = "~/Account/RegisterExternalLogin.aspx";
			if (!tangible.StringHelper.isNullOrEmpty(getReturnUrl()))
			{
				var resolvedReturnUrl = ResolveUrl(getReturnUrl());
				redirectUrl += "?ReturnUrl=" + HttpUtility.UrlEncode(resolvedReturnUrl);
			}

			OpenAuth.RequestAuthentication(provider, redirectUrl);
		}
	}



	private String ReturnUrl;
	public final String getReturnUrl()
	{
		return ReturnUrl;
	}
	public final void setReturnUrl(String value)
	{
		ReturnUrl = value;
	}


	public final java.lang.Iterable<ProviderDetails> GetProviderNames()
	{
		return OpenAuth.AuthenticationClients.GetAll();
	}




	/** 
	 providerDetails control.
	 
	 
	 Campo generado automáticamente.
	 Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
	 
	*/
	protected System.Web.UI.WebControls.ListView providerDetails;

}