package systm_web.account;

import systm_web.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar. 
// </auto-generated>
//------------------------------------------------------------------------------


public class Register extends Page
{
	protected final void Page_Load(Object sender, tangible.EventArgs e)
	{
		RegisterUser.ContinueDestinationPageUrl = Request.QueryString["ReturnUrl"];
	}

	protected final void RegisterUser_CreatedUser(Object sender, tangible.EventArgs e)
	{
//C# TO JAVA CONVERTER TODO TASK: C# to Java Converter could not resolve the named parameters in the following line:
//ORIGINAL LINE: FormsAuthentication.SetAuthCookie(RegisterUser.UserName, createPersistentCookie: false);
		FormsAuthentication.SetAuthCookie(RegisterUser.UserName, createPersistentCookie: false);

		String continueUrl = RegisterUser.ContinueDestinationPageUrl;
		if (!OpenAuth.IsLocalUrl(continueUrl))
		{
			continueUrl = "~/";
		}
		Response.Redirect(continueUrl);
	}



	/** 
	 Control RegisterUser.
	 
	 
	 Campo generado automáticamente.
	 Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
	 
	*/
	protected System.Web.UI.WebControls.CreateUserWizard RegisterUser;

	/** 
	 Control RegisterUserWizardStep.
	 
	 
	 Campo generado automáticamente.
	 Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
	 
	*/
	protected System.Web.UI.WebControls.CreateUserWizardStep RegisterUserWizardStep;
}